spring.application.name=employee-spring-rest-jpa-crud-project
spring.datasource.url=jdbc:mysql://localhost:3306/ctsdb
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8083
spring.jpa.hibernate.ddl-auto=update
